version: 2
updates:
  - directory: '/'
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'âš’ï¸ infrastructure'

  - directory: '/'
    package-ecosystem: 'npm'
    schedule:
      interval: 'daily'
    assignees:
      - 'SocketSomeone'
    commit-message:
      prefix: 'ğŸ”¼'
      prefix-development: 'ğŸ”¼'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 15

  - directory: '/apps/bot'
    package-ecosystem: 'npm'
    schedule:
      interval: 'daily'
    assignees:
      - 'SocketSomeone'
    labels:
      - 'dependencies'
