version: 2
updates:
  - directory: '/'
    package-ecosystem: 'github-actions'
    schedule:
      interval: daily
      time: '00:00'
    reviewers:
      - 'SocketSomeone'
    assignees:
      - 'SocketSomeone'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps):'
      prefix-development: 'chore(deps):'
      include: scope
    open-pull-requests-limit: 10

  - directory: '/'
    package-ecosystem: 'npm'
    schedule:
      interval: daily
      time: '00:00'
    reviewers:
      - 'SocketSomeone'
    assignees:
      - 'SocketSomeone'
    commit-message:
      prefix: 'chore(deps):'
      prefix-development: 'chore(deps):'
      include: scope
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
